// i18n.js — translation data extracted verbatim from katex.html (Phase 6).
// DATA ONLY: the I18N dictionaries and RTL_LANGS set. The applyLanguage()
// logic stays in the app script (it touches the DOM and calls saveSettings).
// Classic script loaded before the app script, so both stay shared globals
// and applyLanguage() reads them exactly as before. Behaviour unchanged.

const I18N = {
  en: { tab_latex:'LaTeX', tab_animate:'Animate', tab_paper:'Paper', tab_calc:'Calc', settings_title:'Settings', settings_autosave:'Auto-save input', settings_dark:'Dark mode', settings_rtl:'RTL layout', settings_lang:'Language', sidebar_header:'Symbols', search_ph:'Search symbols…', recently_used:'Recently Used', placeholder:'Start typing to render LaTeX…', input_label:'LaTeX Input', hint_line:'Each line renders separately.', hint_click:'symbol to insert at cursor.', color_label:'Color', wrap_sel:'Wrap selection', templates_btn:'Templates', templates_title:'Templates', copy_latex:'⊡ Copy LaTeX', copy_img:'📋 Copy Image', share:'🔗 Share', to_latex:'→ LaTeX', wolfram:'↗ Wolfram', align_label:'Align' },
  fr: { tab_latex:'LaTeX', tab_animate:'Animer', tab_paper:'Article', tab_calc:'Calc', settings_title:'Param\xe8tres', settings_autosave:'Sauvegarde auto', settings_dark:'Mode sombre', settings_rtl:'Mise en page RTL', settings_lang:'Langue', sidebar_header:'Symboles', search_ph:'Rechercher…', recently_used:'R\xe9cemment utilis\xe9s', placeholder:'Commencez \xe0 \xe9crire en LaTeX…', input_label:'Entr\xe9e LaTeX', hint_line:'Chaque ligne est rendue s\xe9par\xe9ment.', hint_click:'Symbole pour ins\xe9rer.', color_label:'Couleur', wrap_sel:'Entourer s\xe9lection', templates_btn:'Mod\xe8les', templates_title:'Mod\xe8les', copy_latex:'Copier LaTeX', copy_img:'Copier image', share:'Partager', to_latex:'→ LaTeX', wolfram:'↗ Wolfram', align_label:'Aligner' },
  es: { tab_latex:'LaTeX', tab_animate:'Animar', tab_paper:'Art\xedculo', tab_calc:'Calc', settings_title:'Ajustes', settings_autosave:'Guardado autom\xe1tico', settings_dark:'Modo oscuro', settings_rtl:'Dise\xf1o RTL', settings_lang:'Idioma', sidebar_header:'S\xedmbolos', search_ph:'Buscar s\xedmbolos…', recently_used:'Usados recientemente', placeholder:'Empieza a escribir LaTeX…', input_label:'Entrada LaTeX', hint_line:'Cada l\xednea se renderiza por separado.', hint_click:'S\xedmbolo para insertar.', color_label:'Color', wrap_sel:'Envolver selecci\xf3n', templates_btn:'Plantillas', templates_title:'Plantillas', copy_latex:'Copiar LaTeX', copy_img:'Copiar imagen', share:'Compartir', to_latex:'→ LaTeX', wolfram:'↗ Wolfram', align_label:'Alinear' },
  de: { tab_latex:'LaTeX', tab_animate:'Animieren', tab_paper:'Artikel', tab_calc:'Rechner', settings_title:'Einstellungen', settings_autosave:'Automatisch speichern', settings_dark:'Dunkelmodus', settings_rtl:'RTL-Layout', settings_lang:'Sprache', sidebar_header:'Symbole', search_ph:'Symbole suchen…', recently_used:'Zuletzt verwendet', placeholder:'LaTeX eingeben…', input_label:'LaTeX-Eingabe', hint_line:'Jede Zeile wird separat gerendert.', hint_click:'Symbol zum Einf\xfcgen anklicken.', color_label:'Farbe', wrap_sel:'Auswahl einschlie\xdfen', templates_btn:'Vorlagen', templates_title:'Vorlagen', copy_latex:'LaTeX kopieren', copy_img:'Bild kopieren', share:'Teilen', to_latex:'→ LaTeX', wolfram:'↗ Wolfram', align_label:'Ausrichten' },
  ar: { tab_latex:'لاتك', tab_animate:'تحريك', tab_paper:'مقالة', tab_calc:'حاسبة', settings_title:'الإعدادات', settings_autosave:'حفظ تلقائي', settings_dark:'الوضع الداكن', settings_rtl:'تخطيط RTL', settings_lang:'اللغة', sidebar_header:'الرموز', search_ph:'ابحث عن الرموز…', recently_used:'المستخدمة مؤخراً', placeholder:'ابدأ الكتابة بلاتك…', input_label:'إدخال LaTeX', hint_line:'كل سطر يُعرض بشكل منفصل.', hint_click:'انقر على رمز للإدراج.', color_label:'اللون', wrap_sel:'التفاف التحديد', templates_btn:'القوالب', templates_title:'القوالب', copy_latex:'نسخ LaTeX', copy_img:'نسخ الصورة', share:'مشاركة', to_latex:'إلى LaTeX', wolfram:'وولفرام ↗', align_label:'محاذاة' },
  fa: { tab_latex:'لاتک', tab_animate:'انیمیشن', tab_paper:'مقاله', tab_calc:'ماشین‌حساب', settings_title:'تنظیمات', settings_autosave:'ذخیره خودکار', settings_dark:'حالت تاریک', settings_rtl:'چیدمان راست‌به‌چپ', settings_lang:'زبان', sidebar_header:'نمادها', search_ph:'جستجوی نمادها…', recently_used:'اخیراً استفاده‌شده', placeholder:'لاتک بنویسید…', input_label:'ورودی LaTeX', hint_line:'هر خط جداگانه رندر می‌شود.', hint_click:'روی نماد کلیک کنید.', color_label:'رنگ', wrap_sel:'دربرگرفتن انتخاب', templates_btn:'قالب‌ها', templates_title:'قالب‌ها', copy_latex:'کپی LaTeX', copy_img:'کپی تصویر', share:'اشتراک‌گذاری', to_latex:'به LaTeX', wolfram:'وولفرام ↗', align_label:'تراز' },
  zh: { tab_latex:'LaTeX', tab_animate:'动画', tab_paper:'论文', tab_calc:'计算器', settings_title:'设置', settings_autosave:'自动保存', settings_dark:'深色模式', settings_rtl:'RTL 布局', settings_lang:'语言', sidebar_header:'符号', search_ph:'搜索符号…', recently_used:'最近使用', placeholder:'开始输入 LaTeX…', input_label:'LaTeX 输入', hint_line:'每行单独渲染。', hint_click:'点击符号插入。', color_label:'颜色', wrap_sel:'包裹选区', templates_btn:'模板', templates_title:'模板', copy_latex:'复制 LaTeX', copy_img:'复制图片', share:'分享', to_latex:'→ LaTeX', wolfram:'↗ Wolfram', align_label:'对齐' },
  ja: { tab_latex:'LaTeX', tab_animate:'アニメ', tab_paper:'論文', tab_calc:'計算機', settings_title:'設定', settings_autosave:'自動保存', settings_dark:'ダークモード', settings_rtl:'RTLレイアウト', settings_lang:'言語', sidebar_header:'記号', search_ph:'記号を検索…', recently_used:'最近使用した', placeholder:'LaTeXを入力…', input_label:'LaTeX入力', hint_line:'各行は個別にレンダリングされます。', hint_click:'記号をクリックして挿入。', color_label:'色', wrap_sel:'選択範囲を囲む', templates_btn:'テンプレート', templates_title:'テンプレート', copy_latex:'LaTeXをコピー', copy_img:'画像をコピー', share:'共有', to_latex:'→ LaTeX', wolfram:'↗ Wolfram', align_label:'整列' },
};
const RTL_LANGS = new Set(['ar','fa']);
